### PR TITLE
"Don't autorequire git class"

### PR DESCRIPTION
**Pull request by nibalizer**

### CODE REVIEW

**Comment by mkissam** [comment]
Hi,

I made a pull request to resolve the dependency issues with ruby 1.8.7, but other errors appeared during the build. https://github.com/puppet-community/puppet-git_resource/pull/13

What do you think about ruby 1.8.7 support removal? Everything works well with 1.9.3.

**Comment by nibalizer** [comment]
Most of my infra is still on 1.8.7 so I'd like it to work on 1.8.7. This is a really simple resource so it should be solvable to make it work on 1.8.7

**Comment by mkissam** [comment]
One of the deep-dependency simple dropped 1.8.7 support:
https://github.com/maestrodev/puppet-blacksmith/issues/3

https://github.com/bodeco/bodeco_module_helper using that.

M.

**Comment by nibalizer** [comment]
We don't need blacksmith for 1.8.7 that is a publishing dependency not a runtime dependecy.

**Comment by mkissam** [comment]
Ok, puppet-blacksmith downgraded too for 1.8.7, so the travis-ci pull request is ok now. How can merge?

M.

**Pull request merged**
